[package]
name = "f2elk"
version = "0.1.0"
authors = ["stavinsky"]

#[profile.release]
#lto = true
[dependencies]
reqwest = "0.9.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
regex = "1"
# libc = "0.2.43"
ctrlc = { version = "3.0", features = ["termination"] }
